"""data table

Revision ID: 029a3e85cba1
Revises: f833485769e9
Create Date: 2018-11-04 02:38:48.339824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029a3e85cba1'
down_revision = 'f833485769e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=140), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_date'), 'data', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_date'), table_name='data')
    op.drop_table('data')
    # ### end Alembic commands ###
