"""new fields in user model

Revision ID: f833485769e9
Revises: 632861818084
Create Date: 2018-11-03 19:37:14.559709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f833485769e9'
down_revision = '632861818084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DATARECEIVED')
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    op.create_table('DATARECEIVED',
    sa.Column('ID', sa.INTEGER(), nullable=False),
    sa.Column('DATA', sa.VARCHAR(length=30), nullable=False),
    sa.Column('DATE', sa.DATETIME(), nullable=False),
    sa.Column('RSSI', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###
